// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccountReferences struct {
	Campaigns []*string `json:"campaigns"`
}

type DomainsFilter struct {
	Domains []string `json:"domains"`
	Include bool     `json:"include"`
}

type FirstPartyFilters struct {
	Field *string `json:"field"`
}

type ThirdPartyFilters struct {
	Field *string `json:"field"`
}
